site_name: Iker Iglesias González
site_author: Iker Iglesias González
site_url: https://iker-iglesias.github.io

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs

nav:
  - Sobre Mí: index.md
  - Contacto: contacto.md

markdown_extensions:
  - attr_list
  - md_in_html

plugins: []
