site_name: Mi Página Personal
site_author: Iker Iglesias González
site_url: https://iker-iglesias.github.io

theme:
  name: material
  palette:
    scheme: slate

nav:
  - Inicio: index.md
  - Sobre Mí: sobre-mi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

repo_url: https://github.com/iker-iglesias/iker-iglesias.github.io

markdown_extensions:
  - attr_list
  - md_in_html
